all:
  children:
    webservers:
      hosts:
        server1:
          ansible_host: 10.2.147.114
        server2:
          ansible_host: 10.2.147.168
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ansible_github