name: My first workflow

# The event that triggers this workflow
on: [push]

jobs:
  say-hello:
    # We are using a github hotsted runner runnin the latest ubuntu
    runs-on: ubuntu-latest

    steps:
      # step 1: use a pre-build action to download your code onto the runner
      - name: Checkout code
        uses: actions/checkout@4

      # step 2: run a basic terminal command
      - name: Greet the user
        run: echo "Hello Denis, good lucky with Github Actions!"
